# Generated by Django 5.1.4 on 2026-04-26 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPermisoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa_id', models.IntegerField()),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('requiere_adjunto', models.BooleanField(default=False)),
                ('es_activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tipos_permiso',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa_id', models.IntegerField()),
                ('empleado_id', models.IntegerField()),
                ('tipo_permiso_nombre', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('motivo', models.TextField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_REVISION', 'En revisión'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20)),
                ('adjunto_url', models.URLField(blank=True, null=True)),
                ('comentario_evaluador', models.TextField(blank=True, null=True)),
                ('evaluado_por_id', models.IntegerField(blank=True, null=True)),
                ('fecha_evaluacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(blank=True, null=True)),
                ('tipo_permiso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes', to='solicitud.tipopermisomodel')),
            ],
            options={
                'db_table': 'solicitudes',
                'indexes': [models.Index(fields=['empresa_id', 'estado'], name='solicitudes_empresa_808348_idx'), models.Index(fields=['empleado_id', 'estado'], name='solicitudes_emplead_d532b1_idx'), models.Index(fields=['fecha_inicio', 'fecha_fin'], name='solicitudes_fecha_i_06b8f7_idx')],
            },
        ),
    ]
