# Generated by Django 5.1.4 on 2026-04-26 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlanModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('BASICO', 'Plan Básico'), ('PRO', 'Plan Pro')], max_length=50, unique=True)),
                ('precio_mensual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('limite_usuarios', models.PositiveIntegerField()),
                ('almacenamiento_gb', models.PositiveIntegerField()),
                ('es_activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'planes',
            },
        ),
        migrations.CreateModel(
            name='SuscripcionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa_id', models.IntegerField(unique=True)),
                ('estado', models.CharField(choices=[('TRIAL', 'Periodo de prueba'), ('ACTIVA', 'Activa'), ('VENCIDA', 'Vencida'), ('SUSPENDIDA', 'Suspendida')], default='TRIAL', max_length=20)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin_trial', models.DateTimeField(blank=True, null=True)),
                ('fecha_proxima_facturacion', models.DateTimeField(blank=True, null=True)),
                ('usuarios_activos', models.PositiveIntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(blank=True, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suscripciones', to='suscripcion.planmodel')),
            ],
            options={
                'db_table': 'suscripciones',
                'indexes': [models.Index(fields=['empresa_id', 'estado'], name='suscripcion_empresa_ef1cb9_idx')],
            },
        ),
    ]
