# Generated by Django 5.1.4 on 2026-04-26 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmpleadoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa_id', models.IntegerField()),
                ('usuario_id', models.IntegerField(blank=True, null=True)),
                ('sede_id', models.IntegerField()),
                ('codigo_unico', models.CharField(max_length=20, unique=True)),
                ('nombres', models.CharField(max_length=150)),
                ('apellidos', models.CharField(max_length=150)),
                ('tipo_documento', models.CharField(choices=[('DNI', 'DNI'), ('CE', 'Carné de Extranjería'), ('PASAPORTE', 'Pasaporte'), ('RUC', 'RUC')], max_length=20)),
                ('numero_documento', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=254)),
                ('cargo', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=20)),
                ('fecha_ingreso', models.DateField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'empleados',
                'indexes': [models.Index(fields=['empresa_id', 'estado'], name='empleados_empresa_a3f2d6_idx'), models.Index(fields=['empresa_id', 'area'], name='empleados_empresa_ee0216_idx'), models.Index(fields=['sede_id'], name='empleados_sede_id_45b4d3_idx')],
                'unique_together': {('empresa_id', 'correo'), ('empresa_id', 'numero_documento')},
            },
        ),
    ]
