# Generated by Django 5.1.4 on 2026-04-26 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa_id', models.IntegerField(blank=True, null=True)),
                ('usuario_id', models.IntegerField()),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('canal', models.CharField(choices=[('EMAIL', 'Email'), ('IN_APP', 'In-App'), ('PUSH', 'Push')], max_length=10)),
                ('leida', models.BooleanField(default=False)),
                ('enviada', models.BooleanField(default=False)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'notificaciones',
                'indexes': [models.Index(fields=['usuario_id', 'leida'], name='notificacio_usuario_ef49b7_idx'), models.Index(fields=['usuario_id', 'fecha_creacion'], name='notificacio_usuario_a20c40_idx')],
            },
        ),
    ]
