# Generated by Django 5.1.4 on 2026-04-26 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaLogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa_id', models.IntegerField(blank=True, null=True)),
                ('usuario_id', models.IntegerField(blank=True, null=True)),
                ('rol_usuario', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo_evento', models.CharField(choices=[('INICIO_SESION', 'Inicio de sesión'), ('CIERRE_SESION', 'Cierre de sesión'), ('INTENTO_FALLIDO', 'Intento fallido'), ('CREACION_USUARIO', 'Creación de usuario'), ('MODIFICACION_USUARIO', 'Modificación de usuario'), ('ELIMINACION_USUARIO', 'Eliminación de usuario'), ('CREACION_EMPLEADO', 'Creación de empleado'), ('MODIFICACION_EMPLEADO', 'Modificación de empleado'), ('REGISTRO_ASISTENCIA', 'Registro de asistencia'), ('REGISTRO_MANUAL', 'Registro manual'), ('CREACION_SOLICITUD', 'Creación de solicitud'), ('APROBACION_SOLICITUD', 'Aprobación de solicitud'), ('RECHAZO_SOLICITUD', 'Rechazo de solicitud'), ('SUSPENSION_EMPRESA', 'Suspensión de empresa'), ('ELIMINACION_EMPRESA', 'Eliminación de empresa')], max_length=50)),
                ('descripcion', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('detalles', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'auditoria_log',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['empresa_id', 'timestamp'], name='auditoria_l_empresa_9701e6_idx'), models.Index(fields=['usuario_id'], name='auditoria_l_usuario_57b6f3_idx'), models.Index(fields=['tipo_evento'], name='auditoria_l_tipo_ev_1948a0_idx')],
            },
        ),
    ]
