# Generated by Django 5.1.4 on 2026-04-26 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAsistenciaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa_id', models.IntegerField()),
                ('empleado_id', models.IntegerField()),
                ('sede_id', models.IntegerField()),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida')], max_length=10)),
                ('metodo', models.CharField(choices=[('QR', 'Código QR'), ('MANUAL', 'Registro manual')], max_length=10)),
                ('latitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('es_tardanza', models.BooleanField(default=False)),
                ('es_manual', models.BooleanField(default=False)),
                ('justificacion_manual', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'registros_asistencia',
                'indexes': [models.Index(fields=['empleado_id', 'timestamp'], name='registros_a_emplead_609cb8_idx'), models.Index(fields=['empresa_id', 'timestamp'], name='registros_a_empresa_1cb07c_idx'), models.Index(fields=['sede_id'], name='registros_a_sede_id_8e1c20_idx')],
            },
        ),
        migrations.CreateModel(
            name='TokenQrModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa_id', models.IntegerField()),
                ('sede_id', models.IntegerField()),
                ('token', models.CharField(max_length=64, unique=True)),
                ('expira_en', models.DateTimeField()),
                ('es_activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tokens_qr',
                'indexes': [models.Index(fields=['sede_id', 'es_activo'], name='tokens_qr_sede_id_2cfed6_idx'), models.Index(fields=['token'], name='tokens_qr_token_e79768_idx')],
            },
        ),
    ]
