# Generated by Django 5.1.4 on 2026-04-26 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RolModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa_id', models.IntegerField(blank=True, null=True)),
                ('nombre', models.CharField(choices=[('SUPERADMIN', 'Super Administrador'), ('PROPIETARIO', 'Propietario'), ('ADMIN', 'Administrador'), ('EMPLEADO', 'Empleado')], max_length=50)),
                ('permisos', models.JSONField(default=list)),
                ('es_sistema', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'roles',
                'unique_together': {('empresa_id', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='UsuarioModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa_id', models.IntegerField(blank=True, null=True)),
                ('codigo_unico', models.CharField(max_length=20, unique=True)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('BLOQUEADO', 'Bloqueado')], default='ACTIVO', max_length=20)),
                ('intentos_fallidos', models.PositiveSmallIntegerField(default=0)),
                ('ultimo_acceso', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(blank=True, null=True)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='usuario.rolmodel')),
            ],
            options={
                'db_table': 'usuarios',
                'indexes': [models.Index(fields=['empresa_id'], name='usuarios_empresa_fe0e9f_idx'), models.Index(fields=['codigo_unico'], name='usuarios_codigo__734b7b_idx')],
            },
        ),
    ]
